# Generated by Django 5.1.3 on 2025-01-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quiz_options_quiz_attempts_quiz_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.IntegerField(default=2, help_text='Duration in minutes'),
        ),
    ]
